# -*- coding: utf-8 -*-
"""Text generation with GPT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gC3ET6sYn_TkvtfhLo7JJrLODVb7b9qZ
"""

!pip install -q transformers datasets accelerate sentencepiece

import torch

from datasets import load_dataset

from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

import zipfile
import os

zip_path = "/content/Dataset.zip"
extract_dir = "/content/extracted_dataset/"

# Create extraction directory if it doesn't exist
os.makedirs(extract_dir, exist_ok=True)

# Unzip the dataset
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Load the dataset from the extracted files.
# Assuming the zip file contains text files.
# If your dataset consists of other formats (e.g., JSON, CSV),
# you'll need to change 'text' to 'json' or 'csv' accordingly,
# and adjust the `data_files` argument.
dataset = load_dataset(
    'text', # Specify the type of dataset to load (e.g., 'text', 'json', 'csv')
    data_files=[os.path.join(extract_dir, f) for f in os.listdir(extract_dir) if f.endswith('.txt')]
    # If the zip contains files with other extensions, adjust the filter, or
    # for a single file, provide its explicit path, e.g., data_files=os.path.join(extract_dir, 'my_data.txt')
)

print(dataset)

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

tokenizer.pad_token = tokenizer.eos_token

def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=128
    )

tokenized_dataset = dataset.map(
    tokenize,
    batched=True,
    remove_columns=["text"]
)

# Filter out examples where input_ids might be empty or only contain padding tokens after tokenization
# Assuming tokenized_dataset is a DatasetDict containing a 'train' split
# For GPT2, pad_token is usually eos_token
pad_token_id = tokenizer.pad_token_id
tokenized_dataset["train"] = tokenized_dataset["train"].filter(
    lambda example: any(id != pad_token_id for id in example["input_ids"])
)

# Add a check to ensure the training dataset is not empty after filtering
if len(tokenized_dataset["train"]) == 0:
    raise ValueError("The training dataset is empty after tokenization and filtering. Please check your input text data or tokenizer settings.")

model = GPT2LMHeadModel.from_pretrained("gpt2")

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

training_args = TrainingArguments(

    output_dir="./gpt2-model",

    # overwrite_output_dir=True, # This argument is no longer supported

    num_train_epochs=2,

    per_device_train_batch_size=2,

    save_steps=500,

    save_total_limit=2,

    logging_steps=100,

    prediction_loss_only=True,

    fp16=torch.cuda.is_available()
)

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_dataset["train"],

    data_collator=data_collator
)

trainer.train()

trainer.save_model("./trained_gpt2")

tokenizer.save_pretrained("./trained_gpt2")

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="./trained_gpt2",
    tokenizer="./trained_gpt2"
)

prompt = "Once upon a time"

output = generator(
    prompt,
    max_length=100,
    num_return_sequences=1,
    temperature=0.8,
    top_k=50,
    top_p=0.95
)

print(output[0]["generated_text"])