# -*- coding: utf-8 -*-
"""Text generation with GPT-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKNLjt3waT7ArQrfYnGS49KOBLhikrHI
"""

import torch
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)

from google.colab import files
uploaded = files.upload()

!unzip -o /content/quotes.txt.zip -d /content/

# Verify that train.txt now exists
!ls -F /content/

model_name = "gpt2"

tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

# GPT-2 does not have a default padding token
tokenizer.pad_token = tokenizer.eos_token

model_name = "gpt2"

tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

# GPT-2 does not have a default padding token
tokenizer.pad_token = tokenizer.eos_token

from datasets import load_dataset

def prepare_text_dataset_for_lm(file_path, tokenizer, block_size=128):
    # IMPORTANT: Ensure 'file_path' points to a plain text file, not a zip archive.
    # You need to manually unzip your zip file, e.g., to '/content/quotes.txt'.

    # Load the raw text dataset using the 'datasets' library
    # The 'text' builder can load a single text file.
    raw_datasets = load_dataset("csv", data_files=file_path, split="train")

    # Determine the name of the column containing the text
    # This assumes the text content is in the first column of the CSV.
    text_column_name = raw_datasets.column_names[0]

    # Tokenize the dataset
    def tokenize_function(examples):
        # examples[text_column_name] is a list of strings when batched=True.
        # Pass the list of strings directly to the tokenizer for batch processing.
        # truncation=True will truncate each individual sequence to max_length if it exceeds it.
        return tokenizer(examples[text_column_name], truncation=True, max_length=block_size)

    tokenized_datasets = raw_datasets.map(
        tokenize_function,
        batched=True,
        remove_columns=raw_datasets.column_names, # Remove all original columns
        desc="Running tokenizer on dataset",
    )

    # Group texts into fixed-size chunks (blocks) for language modeling
    # This function is adapted from Hugging Face examples for CLM
    def group_texts(examples):
        # Concatenate all texts.
        concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
        total_length = len(concatenated_examples[list(examples.keys())[0]])
        # We drop the small remainder to ensure all blocks are of 'block_size'.
        total_length = (total_length // block_size) * block_size
        # Split by chunks of block_size.
        result = {
            k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
            for k, t in concatenated_examples.items()
        }
        # For causal language modeling, labels are just a copy of input_ids.
        result["labels"] = result["input_ids"].copy()
        return result

    lm_datasets = tokenized_datasets.map(
        group_texts,
        batched=True,
        desc=f"Grouping texts in chunks of {block_size}",
    )

    return lm_datasets

train_dataset = prepare_text_dataset_for_lm(
    file_path="/content/quotes.csv", # REMINDER: Ensure you have unzipped train.txt.zip to this path
    tokenizer=tokenizer
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

training_args = TrainingArguments(
    output_dir="./gpt2-finetuned",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_steps=500,
    save_total_limit=2,
    logging_steps=100,
    learning_rate=5e-5,
    warmup_steps=100,
    prediction_loss_only=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset
)

trainer.train()

trainer.save_model("./gpt2-finetuned")
tokenizer.save_pretrained("./gpt2-finetuned")

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="./gpt2-finetuned",
    tokenizer=tokenizer
)

prompt = "Happy"

output = generator(
    prompt,
    max_length=100,
    num_return_sequences=1,
    temperature=0.7
)

print(output[0]['generated_text'])